"""Initial schema and Phase 1 updates

Revision ID: 61a20e151959
Revises: 
Create Date: 2026-08-10 19:36:12.946446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a20e151959'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=80), nullable=False),
    sa.Column('product_sku', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('ledger_hash', sa.String(length=128), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('order_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_table('guest_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_key', sa.String(length=180), nullable=False),
    sa.Column('product_id', sa.String(length=80), nullable=False),
    sa.Column('batch_id', sa.String(length=80), nullable=False),
    sa.Column('event_stage', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ledger_hash', sa.String(length=128), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_key')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_code', sa.String(length=80), nullable=False),
    sa.Column('retailer_name', sa.String(length=160), nullable=False),
    sa.Column('retailer_email', sa.String(length=160), nullable=False),
    sa.Column('dealer_id', sa.String(length=80), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=80), nullable=True),
    sa.Column('transporter_id', sa.String(length=80), nullable=True),
    sa.Column('product_sku', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('current_stage', sa.String(length=80), nullable=False),
    sa.Column('batch_id', sa.String(length=80), nullable=True),
    sa.Column('shipment_id', sa.String(length=80), nullable=True),
    sa.Column('origin', sa.String(length=160), nullable=True),
    sa.Column('destination', sa.String(length=160), nullable=True),
    sa.Column('dealer_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retail_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('discrepancy_quantity', sa.Integer(), nullable=False),
    sa.Column('discrepancy_status', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_code')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('reorder_policy', sa.String(length=40), nullable=True),
    sa.Column('safety_stock_qty', sa.Integer(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('available_stock', sa.Integer(), nullable=False),
    sa.Column('reserved_stock', sa.Integer(), nullable=False),
    sa.Column('in_transit', sa.Integer(), nullable=False),
    sa.Column('damaged', sa.Integer(), nullable=False),
    sa.Column('backordered', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('sales_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('sale_amount', sa.Float(), nullable=False),
    sa.Column('retailer_name', sa.String(length=160), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_code', sa.String(length=80), nullable=False),
    sa.Column('product_sku', sa.String(length=80), nullable=False),
    sa.Column('shipment_id', sa.String(length=80), nullable=True),
    sa.Column('event_stage', sa.String(length=80), nullable=False),
    sa.Column('event_status', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('eta_hours', sa.Float(), nullable=True),
    sa.Column('tx_hash', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.String(length=80), nullable=False),
    sa.Column('order_code', sa.String(length=80), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('origin', sa.String(length=160), nullable=True),
    sa.Column('destination', sa.String(length=160), nullable=True),
    sa.Column('eta', sa.String(length=80), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=80), nullable=True),
    sa.Column('assignment_status', sa.String(length=80), nullable=True),
    sa.Column('delay_risk_score', sa.Float(), nullable=True),
    sa.Column('predicted_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('planned_eta', sa.String(length=80), nullable=True),
    sa.Column('route_deviation', sa.String(length=160), nullable=True),
    sa.Column('last_gps_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id')
    )
    op.create_table('supplier_risk_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.String(length=80), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('financial_score', sa.Float(), nullable=False),
    sa.Column('geopolitical_score', sa.Float(), nullable=False),
    sa.Column('operational_score', sa.Float(), nullable=False),
    sa.Column('delivery_score', sa.Float(), nullable=False),
    sa.Column('esg_score', sa.Float(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('parent_supplier_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('supplier_risk_scores')
    op.drop_table('shipments')
    op.drop_table('shipment_events')
    op.drop_table('sales_history')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('notifications')
    op.drop_table('ledger_records')
    op.drop_table('guest_entries')
    op.drop_table('batches')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
