"""Add user management fields

Revision ID: 9e1f11b3b63a
Revises: b93c5a963d95
Create Date: 2026-08-14 00:05:38.562735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1f11b3b63a'
down_revision: Union[str, None] = 'b93c5a963d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False, server_default='default_user'))
        batch_op.add_column(sa.Column('company_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint('uq_users_username', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('phone')
        batch_op.drop_column('company_name')
        batch_op.drop_column('username')
    # ### end Alembic commands ###
